version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh #
    container_name: micro-catalog-app
    ports:
      - 3001:3001
    environment: #apartir dele que podemos colocar o endereço 0.0.0..
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
